---
- name: Calico | Ensure Calico required directories exist
  file: 
    path: "{{ item }}" 
    state: directory
  with_items:
  - "{{ calico_exec_dir }}"

- name: Calico | Drop calico manifest
  template:
    src: calico.yaml.j2
    dest: "{{ calico_exec_dir }}/calico.yaml"
  when: not calico_typha
  notify: "apply calico manifest"

- name: Calico | Drop calico typha manifest
  template:
    src: calico-typha.yaml.j2
    dest: "{{ calico_exec_dir }}/calico.yaml"
  when: calico_typha
  notify: "apply calico manifest"

- name: Calico | Drop calicoctl manifest
  template:
    src: calicoctl.yaml.j2
    dest: "{{ calico_exec_dir }}/calicoctl.yaml"
  register: calicoctl
  notify: "apply calicoctl manifest"
