---
- name: Calico | Ensure Calico required directories exist
  file: path={{ item }} state=directory
  with_items:
    - "{{ calico_exec_dir }}"
    - "{{ calicoctl_config_dir }}"

- name: Calico | Drop calico manifest
  template:
    src: calico.yaml.j2
    dest: "{{ calico_exec_dir }}/calico.yaml"
  register: calico

- name: Calico | Apply calico manifest
  shell: |
    kubectl apply -f "{{ calico_exec_dir }}"/calico.yaml
  run_once: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: calico.changed

- name: Calico | Drop calicoctl manifest
  template:
    src: calicoctl.yaml.j2
    dest: "{{ calico_exec_dir }}/calicoctl.yaml"
  register: calicoctl

- name: Calico | Apply calicoctl manifest
  shell: |
    kubectl apply -f "{{ calico_exec_dir }}"/calicoctl.yaml
  run_once: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
    when: calicoctl.changed
